version: '3'
services:
  node:
    image: "node:12.18.3-alpine3.10"
    user: "node"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/home/node/app
    ports:
      - "8086:8087"
    network_mode: "bridge"
